arguments:
  parameters:
  - name: application-name
    value: pipeline29-app1
  - name: application-name-2
    value: pipeline29-app2
  - name: revision
    value: HEAD
  - name: argocd-server-address
    value: 35.193.141.13:80
  - name: argocd-credentials-secret
    value: argocd-credentials-secret
